
spring:
  datasource:
    url: jdbc:mysql://lsz.env.com:3306/lsz_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  flyway:
    enabled: true