logging:
  level:
    com.lsz.mall.manage: debug

spring:
  datasource:
    url: jdbc:mysql://mall-mysql:3306/lsz_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  flyway:
    enabled: false

  redis:
    host: mall-redis
    port: 6379

pic:
  url: http://localhost:7070/file/image/ # 图片url
  filePath: '/tmp/pic/' # 上传文件路径