logging:
  level:
    com.lsz.mall.manage: debug

spring:
  datasource:
    url: jdbc:mysql://mall-mysql:3306/lsz_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  flyway:
    enabled: false

# 上传文件路径
pic:
  url: http://localhost:7070/file/image/
  filePath: '/tmp/pic'