logging:
  level:
    druid.sql.Statement: debug

spring:
  datasource:
    url: jdbc:mysql://lsz.env.com:3306/lsz_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 参考其他的没用，直接看源码配置，找到这个类LogFilter
    druid.filter.slf4j:
      enabled: true # 开启druid可执行sql日志fterLogEnable
      statement-executable-sql-log-enable: true
      statement-log-error-enabled: true
      result-set-log-enabled: false
      statement-close-after-log-enabled: false
      statement-create-after-log-enabled: false
      result-set-open-after-log-enabled: false
      result-set-close-after-log-enabled: false
      statement-prepare-after-log-enabled: false
      statement-parameter-set-log-enabled: false


  flyway:
    enabled: true