server:
  port: 28018

logging:
  level:
    com.lsz.mall.portal: debug

spring:
  datasource:
    url: jdbc:mysql://mall-mysql:3306/lsz_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: mall-redis
    port: 6379